#include "spadd.h"

#ifdef __EFFCC__
#include <eff.h>
#endif

#include <stdint.h>

/*
 * spadd / SpAdd : sparse matrix-sparse matrix addition -> dense
 * output. This app was originally generated by TACO and modified by hand.
 *
 * Performs A(i, k) + B(k, j) = Z(i, j) (i.e. addition).
 *
 * A is in CSR. B is in CSR. Z is dense.
 *
 * For now, all values are integers.
 *
 * This app shouldn't have memory ordering.
 */

#ifdef EFF_BLD_HAND_OPTIMIZED
__efficient__ void spadd_memset(int32_t *Z, uint32_t count)
{
    __effcc_parallel(16) for (uint32_t i = 0; i < count; i++) { Z[i] = 0; }
    return;
}

__attribute__((always_inline)) void spadd_core_loops(
    const int32_t *A_vals, const uint32_t *A_rows, const uint32_t *A_coords,
    int32_t *Z, uint32_t rows, uint32_t loopIdx, uint32_t loopCount)
{
    for (uint32_t i = loopIdx; i < rows; i += loopCount)
    {
        uint32_t j = A_rows[i + 0];
        uint32_t A_row_end = A_rows[i + 1];

        for (; j < A_row_end; j++)
        {
            uint32_t jA = A_coords[j];
            Z[i * rows + jA] += A_vals[j];
        }
    }
}

__efficient__ void spadd_core(const int32_t *A_vals, const uint32_t *A_rows,
                              const uint32_t *A_coords, int32_t *Z,
                              uint32_t rows)
{
    spadd_core_loops(A_vals, A_rows, A_coords, Z, rows, 0, 4);
    spadd_core_loops(A_vals, A_rows, A_coords, Z, rows, 1, 4);
    spadd_core_loops(A_vals, A_rows, A_coords, Z, rows, 2, 4);
    spadd_core_loops(A_vals, A_rows, A_coords, Z, rows, 3, 4);
    return;
}

void spadd(const int32_t *A_vals, const uint32_t *A_rows,
           const uint32_t *A_coords, const int32_t *B_vals,
           const uint32_t *B_rows, const uint32_t *B_coords, int32_t *Z,
           uint32_t rows)
{
    // initialize Z to 0
    spadd_memset(Z, rows * rows);

    // add A to Z
    spadd_core(A_vals, A_rows, A_coords, Z, rows);

    // add B to Z
    spadd_core(B_vals, B_rows, B_coords, Z, rows);

    return;
}
#else
__efficient__ void spadd(const int32_t *A_vals, const uint32_t *A_rows,
                         const uint32_t *A_coords, const int32_t *B_vals,
                         const uint32_t *B_rows, const uint32_t *B_coords,
                         int32_t *Z, uint32_t rows)
{
    /*
     * Iterate over all rows
     */
    for (uint32_t i = 0; i < rows; i++)
    {
        uint32_t jA = A_rows[i + 0];
        uint32_t A_row_end = A_rows[i + 1];
        uint32_t jB = B_rows[i + 0];
        uint32_t B_row_end = B_rows[i + 1];
        uint32_t base = i * rows;

        /*
         * Merge/union over sparse rows, A[i] and B[i]
         */
        while (jA < A_row_end || jB < B_row_end)
        {
            uint32_t jA0 = A_coords[jA];
            uint32_t jB0 = B_coords[jB];
            uint32_t j = (jA0 < jB0) ? jA0 : jB0;

            uint32_t sum = 0;
            sum += (jA0 == j) ? A_vals[jA] : 0;
            sum += (jB0 == j) ? B_vals[jB] : 0;

            if (sum)
            {
                Z[base + j] = sum;
            }

            jA += (uint32_t)(jA0 == j);
            jB += (uint32_t)(jB0 == j);
        }
    }
    return;
}

#endif
