#ifdef __EFFCC__
#include <eff.h>
#endif

#include <stdint.h>

#include "spmspv.h"

/*
 * spmspv: Sparse matrix-sparse vector multiplication, dense output.
 *
 * The matrix is in CSR format.
 *
 * This kernel was originally generated by TACO and modified by hand.
 */
#ifdef EFF_BLD_HAND_OPTIMIZED
__efficient__ void spmspv(const uint32_t *a_indptr, const uint32_t *a_indices,
                          const int32_t *a_data, uint32_t a_nrows,
                          const uint32_t *x_indices, const int32_t *x_data,
                          const int32_t xnnz, int32_t *z)
{
    // Computes 5 elements of the output vector at once.
    for (uint32_t j = 0; j < a_nrows; j += 5)
    {
        int32_t B0_col_start = a_indptr[j];
        int32_t B0_col_end = a_indptr[j + 1];
        int32_t B1_col_start = B0_col_end;
        int32_t B1_col_end = j + 1 < a_nrows ? a_indptr[j + 2] : 0;
        int32_t B2_col_start = B1_col_end;
        int32_t B2_col_end = j + 2 < a_nrows ? a_indptr[j + 3] : 0;
        int32_t B3_col_start = B2_col_end;
        int32_t B3_col_end = j + 3 < a_nrows ? a_indptr[j + 4] : 0;
        int32_t B4_col_start = B3_col_end;
        int32_t B4_col_end = j + 4 < a_nrows ? a_indptr[j + 5] : 0;

        int32_t iB0 = B0_col_start - 1;
        int32_t iB1 = B1_col_start - 1;
        int32_t iB2 = B2_col_start - 1;
        int32_t iB3 = B3_col_start - 1;
        int32_t iB4 = B4_col_start - 1;

        int32_t dot_prod0 = 0;
        int32_t dot_prod1 = 0;
        int32_t dot_prod2 = 0;
        int32_t dot_prod3 = 0;
        int32_t dot_prod4 = 0;

        int32_t B0_Col = -1;
        int32_t B1_Col = -1;
        int32_t B2_Col = -1;
        int32_t B3_Col = -1;
        int32_t B4_Col = -1;

        // Sparse dot product
        // Middle loop unrolled 5 times
        for (int iA = 0; iA < xnnz; iA++)
        {
            int32_t A_col = x_indices[iA];

            // Fast-forward B pointers
            if (iB0 < B0_col_end && B0_Col < A_col)
            {
                do
                {
                    B0_Col = a_indices[++iB0];
                } while (B0_Col < A_col && iB0 < B0_col_end);
            }

            if (iB1 < B1_col_end && B1_Col < A_col)
            {
                do
                {
                    B1_Col = a_indices[++iB1];
                } while (B1_Col < A_col && iB1 < B1_col_end);
            }

            if (iB2 < B2_col_end && B2_Col < A_col)
            {
                do
                {
                    B2_Col = a_indices[++iB2];
                } while (B2_Col < A_col && iB2 < B2_col_end);
            }

            if (iB3 < B3_col_end && B3_Col < A_col)
            {
                do
                {
                    B3_Col = a_indices[++iB3];
                } while (B3_Col < A_col && iB3 < B3_col_end);
            }

            if (iB4 < B4_col_end && B4_Col < A_col)
            {
                do
                {
                    B4_Col = a_indices[++iB4];
                } while (B4_Col < A_col && iB4 < B4_col_end);
            }

            // Conditional dot products
            if (B0_Col == A_col && iB0 < B0_col_end)
            {
                dot_prod0 += x_data[iA] * a_data[iB0];
            }
            if (B1_Col == A_col && iB1 < B1_col_end)
            {
                dot_prod1 += x_data[iA] * a_data[iB1];
            }
            if (B2_Col == A_col && iB2 < B2_col_end)
            {
                dot_prod2 += x_data[iA] * a_data[iB2];
            }
            if (B3_Col == A_col && iB3 < B3_col_end)
            {
                dot_prod3 += x_data[iA] * a_data[iB3];
            }
            if (B4_Col == A_col && iB4 < B4_col_end)
            {
                dot_prod4 += x_data[iA] * a_data[iB4];
            }
        }

        // Store dot products
        z[j] = dot_prod0;
        if (j + 1 < a_nrows)
            z[j + 1] = dot_prod1;
        if (j + 2 < a_nrows)
            z[j + 2] = dot_prod2;
        if (j + 3 < a_nrows)
            z[j + 3] = dot_prod3;
        if (j + 4 < a_nrows)
            z[j + 4] = dot_prod4;
    }
    return;
}
#else
__efficient__ void spmspv(const uint32_t *a_indptr, const uint32_t *a_indices,
                          const int32_t *a_data, uint32_t a_nrows,
                          const uint32_t *x_indices, const int32_t *x_data,
                          const int32_t xnnz, int32_t *z)
{
    /*
     * Iterates over each sparse row of A and performs a
     * stream-join/intersection with the sparse vector x. The result is the dot
     * product of the two vectors.
     */

    __effcc_parallel(UNROLLING_FACTOR) for (uint32_t i = 0; i < a_nrows; i++)
    {
        int w = 0;

        int32_t jA = a_indptr[i];
        int32_t A_row_end = a_indptr[i + 1];
        int32_t jx = 0;
        int32_t x_end = xnnz;

        /*
         * Stream-join/intersection of the two vectors.
         */
        while (jA < A_row_end && jx < x_end)
        {
            int32_t jA0 = a_indices[jA];
            int32_t jx0 = x_indices[jx];
            int32_t j = (jA0 < jx0) ? jA0 : jx0;
            if (jA0 == j && jx0 == j)
            {
                w += a_data[jA] * x_data[jx];
            }
            jA += (int32_t)(jA0 == j);
            jx += (int32_t)(jx0 == j);
        }

        z[i] = w;
    }
}

#endif
