#!/usr/bin/env python
"""
gen_hamming_window.py - Generate the Hamming window coefficients used in the STFT
inside extract_features.py.

The STFT calls:
    tf.signal.hamming_window(window_size_samples, periodic=False)

which produces a symmetric Hamming window:
    w[n] = 0.54 - 0.46 * cos(2*pi*n / (N-1)),  n = 0 .. N-1

Usage
-----
  # Print float32 values to stdout
  python gen_hamming_window.py

  # Write a C header
  python gen_hamming_window.py -o hamming_window.h

  # Different window size
  python gen_hamming_window.py --window_size 512 -o hamming_window.h
"""

import argparse
import math
import os
import subprocess

# Q1.15: 1 sign bit + 15 fractional bits, stored as int16_t.
# Representable range: [-1, 1).  Scale factor = 2^15 = 32768.
Q15 = 32768


def hamming_window(n: int) -> list[float]:
    """Symmetric Hamming window of length n (periodic=False).

    Matches tf.signal.hamming_window(n, periodic=False).
    """
    if n == 1:
        return [1.0]
    return [0.54 - 0.46 * math.cos(2.0 * math.pi * i / (n - 1)) for i in range(n)]


def to_q15(coeffs: list[float]) -> list[int]:
    """Convert float coefficients in [0, 1] to Q1.15 int16 values.

    Rounds half-away from zero and clips to the int16 range [-32768, 32767].
    The Hamming window lies in [0.08, 1.0], so values are non-negative and
    the maximum representable value (1.0) maps to 32767 (not 32768, which
    would overflow), giving a worst-case rounding error of ~3e-5.
    """
    result = []
    for v in coeffs:
        q = int(math.floor(v * Q15 + 0.5))  # round half-up
        q = max(-32768, min(32767, q))  # clip to int16
        result.append(q)
    return result


def write_header(q15_coeffs: list[int], output_path: str, window_size: int) -> None:
    base = os.path.splitext(os.path.basename(output_path))[0]
    var_name = base.replace("-", "_").replace(".", "_").replace(" ", "_")

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by gen_hamming_window.py\n")
        f.write(f" * Symmetric Hamming window, length {window_size}, Q1.15 format\n")
        f.write(f" * w[n] = 0.54 - 0.46 * cos(2*pi*n / (N-1))\n")
        f.write(f" * Stored as int16_t; true value = coeff / 32768.0\n")
        f.write(" */\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define {var_name.upper()}_LENGTH {window_size}\n\n")
        f.write(f"static const int16_t {var_name}[{var_name.upper()}_LENGTH] = {{\n")

        per_line = 16
        for i in range(0, len(q15_coeffs), per_line):
            chunk = q15_coeffs[i : i + per_line]
            line = ", ".join(f"{v:6d}" for v in chunk)
            comma = "," if i + per_line < len(q15_coeffs) else ""
            f.write(f"    {line}{comma}\n")

        f.write("};\n")


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--window_size",
        type=int,
        default=1024,
        help="Window length in samples (default 1024, matching extract_features.py).",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=None,
        help="Output path. Use a .h extension for a C header file. "
        "Defaults to printing values to stdout.",
    )
    args = parser.parse_args()

    coeffs = hamming_window(args.window_size)
    q15_coeffs = to_q15(coeffs)

    if args.output is None:
        print(f'{"idx":>4}  {"float":>14}  {"Q1.15":>6}')
        for i, (f_val, q_val) in enumerate(zip(coeffs, q15_coeffs)):
            print(f"{i:4d}  {f_val:14.10f}  {q_val:6d}")
    elif args.output.endswith(".h"):
        write_header(q15_coeffs, args.output, args.window_size)
        subprocess.run(["clang-format", "-style=file", "-i", args.output], check=True)
        print(
            f"Wrote {len(q15_coeffs)}-coefficient Q1.15 Hamming window to {args.output}"
        )
    else:
        import numpy as np

        arr = np.array(q15_coeffs, dtype=np.int16)
        np.save(args.output, arr)
        print(
            f"Saved {len(q15_coeffs)}-coefficient Q1.15 Hamming window to {args.output}"
        )


if __name__ == "__main__":
    main()
