#ifdef __EFFCC__
#include <eff.h>
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "biquad_filter.h"

#define NUM_ITERATIONS 1

// If changed, the CMakeLists.txt file will need to be updated so
// gen_data.py follows the new size
#define INPUT_SIZE 4096
#define NUM_ITERATIONS 100

// Sample data generated by gen_data.py
extern const int16_t sample_input[INPUT_SIZE];
extern const int16_t expected_output[INPUT_SIZE];

// Low pass filter centered at 300Hz Q=0.72
float poles_coeffs[2] = {-1.8400889269370049f, 0.8523343179964432f};
float zeros_coeffs[3] = {0.003061347764859629f, 0.006122695529719258f, 0.003061347764859629f};

_Alignas(2) int16_t output[INPUT_SIZE];

int main()
{
    for (int iter = 0; iter < NUM_ITERATIONS; iter++)
    {
        biquad_filter(sample_input, output, INPUT_SIZE, poles_coeffs, zeros_coeffs);
    }

    // Compute error
    int32_t err = 0;
    for (int i = 100; i < INPUT_SIZE; i++)
    {
        err += abs(output[i] - expected_output[i]);
    }

    if ((err / (INPUT_SIZE - 100)) > 660)
    {
        printf("[biquad_filter] FAIL - Average error exceeded threshold: %d\r\n", err / (INPUT_SIZE - 100));
        return 1;
    }

    printf("[biquad_filter] PASS\r\n");
    return 0;
}
