#ifdef __EFFCC__
#include <eff.h>
#endif

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include "biquad_filter.h"

// Number of times the measured region runs. The biquad kernel is short relative
// to the EVK sample period (25 ms on early EVK firmware), so it is run in a loop
// and the measured runtime and energy are divided by this count in
// post-processing. Pass the same value to process-energy.py via --iters.
//
// This is a starting point: if the measured region does not run comfortably
// longer than the sample period, increase NUM_ITERATIONS and measure again.
#define NUM_ITERATIONS 1000

// If changed, the CMakeLists.txt file will need to be updated so
// gen_data.py follows the new size
#define INPUT_SIZE 16384

// Sample data generated by gen_data.py
extern const int16_t sample_input[INPUT_SIZE];
extern const int16_t expected_output[INPUT_SIZE];

// Low pass filter centered at 300Hz Q=0.72
float poles_coeffs[2] = {-1.8400889269370049f, 0.8523343179964432f};
float zeros_coeffs[3] = {0.003061347764859629f, 0.006122695529719258f, 0.003061347764859629f};

_Alignas(2) int16_t output[INPUT_SIZE];

int main()
{
#ifdef __EFFCC__
    // Configure AON4 as a GPIO output so the EVK can mark the measured region.
    // The on-board RP2040 monitors AON4/AON5; AON4 is the usual profiling pin
    // (AON0-AON3 are reserved for the programmer interface).
    eff_pinmux_set(PINMUX_AON, PINMUX_GPIO);
    eff_gpio_dir_set(GPIO_AON, GPIO_PIN_4, EFF_GPIO_OUT);

    // Hold AON4 high long enough for the EVK sampler to observe the high level.
    // Otherwise, if AON4 starts low after reset, the RP2040 can miss the falling
    // edge that marks the start of the measured region.
    eff_gpio_set(GPIO_AON, GPIO_PIN_4);
    sleep(1);

    // Falling edge marks the start of the measured region.
    eff_gpio_clear(GPIO_AON, GPIO_PIN_4);
#endif

    for (int iter = 0; iter < NUM_ITERATIONS; iter++)
    {
        biquad_filter(sample_input, output, INPUT_SIZE, poles_coeffs, zeros_coeffs);
    }

#ifdef __EFFCC__
    // Rising edge marks the end of the measured region.
    eff_gpio_set(GPIO_AON, GPIO_PIN_4);
#endif

    // Compute error (outside the measured region)
    int32_t err = 0;
    for (int i = 100; i < INPUT_SIZE; i++)
    {
        err += abs(output[i] - expected_output[i]);
    }

    if ((err / (INPUT_SIZE - 100)) > 660)
    {
        printf("[biquad_filter] FAIL - Average error exceeded threshold: %d\r\n", err / (INPUT_SIZE - 100));
        return 1;
    }

    printf("[biquad_filter] PASS\r\n");
    return 0;
}
