"""
Generate f450_cache_q20.h — the TinyMPC infinite-horizon cache for a
**Hawk's Work F450**-class quadrotor (DJI F450 flame-wheel geometry).

Standard 12-state hover linearization (Mellinger & Kumar), same state/control
layout as the Crazyflie example so it reuses the generic solver:

    x = [ px py pz | roll pitch yaw | vx vy vz | wx wy wz ]   (12)
    u = per-motor thrust, normalized by hover thrust, delta about hover   (4)
        u_i = 0 at hover; u_i = +1 means +1 hover-thrust extra on motor i

Near hover the state coupling A depends only on gravity and dt; the mass /
inertia / geometry enter entirely through B. We discretize at 50 Hz, fold the
ADMM penalty rho into the DARE, solve for the infinite-horizon cache, and
quantize to Q20 for the E1x fabric (int32, no float, no 64-bit divide online).

  python3 gen_f450_cache.py        # -> f450_cache_q20.h   (needs numpy + scipy)

── F450 parameters (typical; adjust to your airframe) ────────────────────────
All are documented estimates for a ~1.2 kg F450 on 3S with 920 kV / 1045 props.
Refine m, J, L from your own weigh-in / bifilar-pendulum ID for a tighter model.
"""
import warnings
import numpy as np
from scipy.linalg import expm, solve_discrete_are
warnings.filterwarnings("ignore")   # scipy expm Pade-order picker emits spurious norm warnings

# ── airframe ────────────────────────────────────────────────────────────────
m    = 1.2        # all-up mass (kg)  — F450 frame + 4S/3S + payload
Ixx  = 0.012      # roll inertia  (kg m^2)
Iyy  = 0.012      # pitch inertia (kg m^2)
Izz  = 0.022      # yaw inertia   (kg m^2)
L    = 0.225      # centre-to-motor distance (m) — 450 mm diagonal wheelbase / 2
d    = L / np.sqrt(2.0)   # X-config moment arm about roll/pitch axes (m)
cT   = 0.016      # motor drag-torque / thrust ratio (m) — yaw authority, ~10" prop
g    = 9.81
DT   = 0.02       # 50 Hz

f_h  = m * g / 4.0            # hover thrust per motor (N)
NX, NU = 12, 4

# ── control allocation (X config), per-unit-u (u normalized by f_h) ──────────
# motors: 1=front-right 2=rear-left 3=front-left 4=rear-right, CCW=1,2  CW=3,4
#   thrust = u1+u2+u3+u4
#   roll   = -u1 +u2 +u3 -u4     (about +x, right-hand)
#   pitch  =  u1 -u2 +u3 -u4     (about +y)
#   yaw    =  u1 +u2 -u3 -u4     (prop drag, CCW positive)
roll_mix  = np.array([-1.0,  1.0,  1.0, -1.0])
pitch_mix = np.array([ 1.0, -1.0,  1.0, -1.0])
yaw_mix   = np.array([ 1.0,  1.0, -1.0, -1.0])

# ── continuous linearized hover dynamics  xdot = Ac x + Bc u ─────────────────
Ac = np.zeros((NX, NX))
Ac[0, 6] = 1.0; Ac[1, 7] = 1.0; Ac[2, 8] = 1.0      # pdot = v
Ac[3, 9] = 1.0; Ac[4,10] = 1.0; Ac[5,11] = 1.0      # Theta_dot = omega (small angle)
Ac[6, 4] =  g                                       # vx_dot =  g * pitch
Ac[7, 3] = -g                                       # vy_dot = -g * roll

Bc = np.zeros((NX, NU))
Bc[8, :]  = (f_h / m)        * np.ones(4)           # vz_dot  = (f_h/m) * sum(u)
Bc[9, :]  = (f_h * d / Ixx)  * roll_mix             # wx_dot
Bc[10, :] = (f_h * d / Iyy)  * pitch_mix            # wy_dot
Bc[11, :] = (f_h * cT / Izz) * yaw_mix              # wz_dot

# ── discretize (matrix exponential of the augmented system) ──────────────────
M = np.zeros((NX + NU, NX + NU)); M[:NX, :NX] = Ac; M[:NX, NX:] = Bc
Md = expm(M * DT); A = Md[:NX, :NX]; B = Md[:NX, NX:]

# ── TinyMPC cost + cache (augmented DARE, rho folded in) ─────────────────────
Q = np.array([100.,100.,100.,  10.,10.,10.,  4.,4.,4.,  0.5,0.5,0.5])  # pos att vel rate
R = np.array([1., 1., 1., 1.])       # per-motor effort
RHO = 5.0
U_LIM = 0.9                          # |u| box: down to ~0 thrust, up to ~2x hover
N   = 10
SCALE = 20

Qt = np.diag(Q + RHO); Rt = np.diag(R + RHO)
P  = solve_discrete_are(A, B, Qt, Rt)
Quu_inv = np.linalg.inv(Rt + B.T @ P @ B)
Kinf    = Quu_inv @ (B.T @ P @ A)
AmBKt   = (A - B @ Kinf).T
sr = np.max(np.abs(np.linalg.eigvals(A - B @ Kinf)))
print(f"F450: m={m} kg  J=({Ixx},{Iyy},{Izz})  L={L} m  f_hover={f_h:.2f} N/motor")
print(f"closed-loop spectral radius {sr:.4f} ({'stable' if sr < 1 else 'UNSTABLE'})")
print(f"max|Kinf|={np.abs(Kinf).max():.2f}  max|A|={np.abs(A).max():.2f}  "
      f"(Q20 int32 range +-{2**11})")

ONE = 1 << SCALE
def qi(x): return int(round(float(x) * ONE))
def flat(a): return ",".join(str(qi(v)) for v in np.asarray(a).ravel())

H = [f"/* Auto-generated by gen_f450_cache.py — Hawk's Work F450 TinyMPC cache (Q20). */",
     f"/* m={m}kg J=({Ixx},{Iyy},{Izz}) L={L}m dt={DT}s N={N} rho={int(RHO)} sr={sr:.4f} */",
     "#pragma once\n#include <stdint.h>",
     f"#define F450_NX {NX}\n#define F450_NU {NU}\n#define F450_N {N}\n#define F450_RHO {int(RHO)}\n#define F450Q {SCALE}",
     f"#define F450_UMIN_Q20 ({qi(-U_LIM)})\n#define F450_UMAX_Q20 ({qi(U_LIM)})",
     f"static const int32_t F450_A_Q20[{NX*NX}]={{{flat(A)}}};",
     f"static const int32_t F450_B_Q20[{NX*NU}]={{{flat(B)}}};",
     f"static const int32_t F450_Kinf_Q20[{NU*NX}]={{{flat(Kinf)}}};",
     f"static const int32_t F450_Quu_Q20[{NU*NU}]={{{flat(Quu_inv)}}};",
     f"static const int32_t F450_AmBKt_Q20[{NX*NX}]={{{flat(AmBKt)}}};"]
open("f450_cache_q20.h", "w").write("\n".join(H) + "\n")
print("wrote f450_cache_q20.h")
